"""initial migration

Revision ID: ebc8139b0434
Revises: 
Create Date: 2024-11-07 12:37:50.880999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ebc8139b0434'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tvprogramgenrelink')
    op.drop_table('tvprogram')
    op.drop_table('tvpubstate')
    op.drop_table('tvchannel')
    op.drop_table('tvgenres')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tvgenres',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('generoInf', sa.VARCHAR(), nullable=True),
    sa.Column('generoInfUid', sa.VARCHAR(), nullable=True),
    sa.Column('generoId', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tvchannel',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('htmlUrl', sa.VARCHAR(), nullable=True),
    sa.Column('uid', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tvpubstate',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('code', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tvprogram',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('htmlUrl', sa.VARCHAR(), nullable=False),
    sa.Column('uid', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('language', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('emission', sa.VARCHAR(), nullable=True),
    sa.Column('publicationDate', sa.DATETIME(), nullable=True),
    sa.Column('orden', sa.INTEGER(), nullable=True),
    sa.Column('imageSEO', sa.VARCHAR(), nullable=True),
    sa.Column('logo', sa.VARCHAR(), nullable=True),
    sa.Column('thumbnail', sa.VARCHAR(), nullable=True),
    sa.Column('ageRangeUid', sa.VARCHAR(), nullable=True),
    sa.Column('ageRange', sa.VARCHAR(), nullable=True),
    sa.Column('contentType', sa.VARCHAR(), nullable=True),
    sa.Column('sgce', sa.VARCHAR(), nullable=True),
    sa.Column('programType', sa.VARCHAR(), nullable=True),
    sa.Column('programTypeId', sa.INTEGER(), nullable=True),
    sa.Column('isComplete', sa.BOOLEAN(), nullable=True),
    sa.Column('numSeasons', sa.INTEGER(), nullable=True),
    sa.Column('director', sa.VARCHAR(), nullable=True),
    sa.Column('producedBy', sa.VARCHAR(), nullable=True),
    sa.Column('showMan', sa.VARCHAR(), nullable=True),
    sa.Column('casting', sa.VARCHAR(), nullable=True),
    sa.Column('technicalTeam', sa.VARCHAR(), nullable=True),
    sa.Column('idWiki', sa.VARCHAR(), nullable=True),
    sa.Column('pubState_id', sa.INTEGER(), nullable=True),
    sa.Column('channel_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['tvchannel.id'], ),
    sa.ForeignKeyConstraint(['pubState_id'], ['tvpubstate.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tvprogramgenrelink',
    sa.Column('program_id', sa.INTEGER(), nullable=False),
    sa.Column('genre_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['tvgenres.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['tvprogram.id'], ),
    sa.PrimaryKeyConstraint('program_id', 'genre_id')
    )
    # ### end Alembic commands ###
