#################
### MONITORING###
#################
###
GET http://127.0.0.1:8000/monitor/cpu

###
GET http://127.0.0.1:8000/monitor/cpu

###
GET http://127.0.0.1:8000/monitor/cpu


##################
###    RTVE    ###
##################
###
GET http://127.0.0.1:8000/rtve/ping
