"""RTVE Tables added Refactor

Revision ID: 0202dd414a22
Revises: 1fb14291d432
Create Date: 2024-11-14 17:30:31.829946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0202dd414a22'
down_revision: Union[str, None] = '1fb14291d432'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('htmlUrl', sa.String(), nullable=True),
    sa.Column('uid', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channel_id'), 'channel', ['id'], unique=False)
    op.create_table('genre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('generoInf', sa.String(), nullable=True),
    sa.Column('generoInfUid', sa.String(), nullable=True),
    sa.Column('generoId', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_genre_id'), 'genre', ['id'], unique=False)
    op.create_table('pub_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pub_state_id'), 'pub_state', ['id'], unique=False)
    op.create_table('program',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('htmlUrl', sa.String(), nullable=True),
    sa.Column('uid', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('emission', sa.String(), nullable=True),
    sa.Column('publicationDate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.Column('pub_state_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ),
    sa.ForeignKeyConstraint(['pub_state_id'], ['pub_state.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_program_id'), 'program', ['id'], unique=False)
    op.create_table('program_genre',
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['program.id'], ),
    sa.PrimaryKeyConstraint('program_id', 'genre_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('program_genre')
    op.drop_index(op.f('ix_program_id'), table_name='program')
    op.drop_table('program')
    op.drop_index(op.f('ix_pub_state_id'), table_name='pub_state')
    op.drop_table('pub_state')
    op.drop_index(op.f('ix_genre_id'), table_name='genre')
    op.drop_table('genre')
    op.drop_index(op.f('ix_channel_id'), table_name='channel')
    op.drop_table('channel')
    # ### end Alembic commands ###
