"""Member Alias Added

Revision ID: 1fb14291d432
Revises: 454926c36f0d
Create Date: 2024-11-13 13:57:56.859922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fb14291d432'
down_revision: Union[str, None] = '454926c36f0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('alias', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'alias')
    # ### end Alembic commands ###
