"""Age Added

Revision ID: 454926c36f0d
Revises: 6ab37e284c8d
Create Date: 2024-11-13 13:57:24.514613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '454926c36f0d'
down_revision: Union[str, None] = '6ab37e284c8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('age', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'age')
    # ### end Alembic commands ###
