"""RTVE PubState add  programs

Revision ID: 76e4893ba814
Revises: a3548ff5ebc8
Create Date: 2024-11-15 12:12:59.163670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76e4893ba814'
down_revision: Union[str, None] = 'a3548ff5ebc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
