"""RTVE Progras added age and personal

Revision ID: b027ef30ed78
Revises: 76e4893ba814
Create Date: 2024-11-15 13:36:36.258141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b027ef30ed78'
down_revision: Union[str, None] = '76e4893ba814'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('program', sa.Column('director', sa.String(), nullable=True))
    op.add_column('program', sa.Column('producedBy', sa.String(), nullable=True))
    op.add_column('program', sa.Column('showMan', sa.String(), nullable=True))
    op.add_column('program', sa.Column('ageRangeUid', sa.String(), nullable=True))
    op.add_column('program', sa.Column('ageRange', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('program', 'ageRange')
    op.drop_column('program', 'ageRangeUid')
    op.drop_column('program', 'showMan')
    op.drop_column('program', 'producedBy')
    op.drop_column('program', 'director')
    # ### end Alembic commands ###
